<?php
/**
 * Declare what blocks are provided by this module.
 * Implements hook_block_info().
 */
function slide_block_info(){
    $block['slide'] = array(
        'info' => t('slide'),
        'cache' => DRUPAL_NO_CACHE,
    );
    return $block;
}
 
/**
 * Define what our block is going to look like.
 * Implements hook_block_view().
 */
function slide_block_view($block_key){
    $block = array();
     
    if($block_key == 'slide'){ //We only want to define the content of OUR block
        //This is the title of the block.
        $block['subject'] = t('slide Countdown');
 
        //Define the block content.
        $block['content'] = custom_contents();
    }
 
    return $block;
}

function custom_contents() {
          return '
            </p><div class="body">
              Hello World, this is a example custom Block
            </div><p>
          ';
        }